### ISSUE TITLE
Software Checklist 

### ISSUE THREAD

**Issue by DininduSenanayake** [GenomicsAotearoa/long-read-assembly#2]
- [x] [Seqkit](https://bioinf.shenwei.me/seqkit/) #8 
- [x] [CutAdapt](https://cutadapt.readthedocs.io/en/stable/) #11 
- [x] [Nanocomp](https://github.com/wdecoster/nanocomp) #13 
- [x] [Best](https://github.com/google/best) #5 
- [x] Verkko 1.3.1  #1 
- [x] Hifiasm (latest) #4 
- [x] Yak (latest) #9 
- [x] [mashmap](https://github.com/marbl/MashMap/tree/master) (including [generatedotplot] #7 (https://github.com/marbl/MashMap/blob/master/scripts/generateDotPlot))
- [x] [meryl](https://github.com/marbl/meryl) #6 
- [x] Merqury (https://github.com/marbl/merqury) #6 
- [x] [Winnowmap](https://github.com/marbl/winnowmap) #3 
- [x] [gfastats](https://github.com/vgl-hub/gfastats) #10 
- [x] minimap2 & k8 (for asmgene)  #12 
- [x] [FCS](https://github.com/ncbi/fcs)  #14  
    - This tool is a bit odd, you don't really install it you just download the runner script. The runner script reads in arguments and decides which Docker command to run. (So the take home is that we just need to be able to run either Docker or Singularity)
 - [x] Liftoff #15 
 - [x] ModDotPlot #16

**Comment by juklucas** [comment]
Could you please also install
* [ModDotPlot](https://github.com/marbl/ModDotPlot)
* [Liftoff](https://github.com/agshumate/Liftoff)

**Comment by DininduSenanayake** [comment]
@juklucas LIftoff is ready as per #15

**Comment by DininduSenanayake** [comment]
@juklucas ModDotPlot is ready as per #16
